### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by lionhylra** [facebook/Shimmer#52]
I created a view(shimmerView) and added a FBShimmerView onto it. Then I make my app do this loop:
Show the shimmerView, go to other views, go to shimmerView, go to other views...  

Everything was normal except that something increased in the memory.
So I opened Instrument to see what happened. And it showed that instances of FBShimmeringLayer and FBShimmeringMaskLayer increased by one every tine a FBShimmerView is displayed. That means when a FBShimmerView is deallocated, the FBShimmeringLayer is persisted in the memory.  
See the screenshot below:
![screenshot 2015-10-21 17 17 44](https://cloud.githubusercontent.com/assets/4083480/10629191/6e3ed6d2-7818-11e5-897e-cd52a6117f26.png)

**Comment by grp** [comment]
Do you have the latest commit in place? There was a retain cycle that got fixed: 32ded5bf7bd3a0dbe2f719dbb6e8ef77c3a1d8ee

**Comment by lionhylra** [comment]
Thanks. I used the package on cocoaPods.

**Comment by grp** [comment]
I'll put out an update for that soon, but for now you should be able to point Cocoapods to that commit. Thanks for filing!

**Comment by lionhylra** [comment]
I just use the latest commit and test it in the Instrument. The FBShimmeringLayer and FBShimmeringMaskLayer are still retained. Could you have a check?

**Comment by grp** [comment]
When you say the instances increase when it is 'displayed', what do you mean by that? Are you asking it to start shimmering? Are you simply adding it to the view hierarchy? Creating a new `FBShimmeringView`?

I would try limiting the operations you perform on the shimmering view, then go into the one operation that seems to cause the issue and find where it's allocating a new object.

**Comment by grp** [comment]
I pushed another commit that might help. Let me know if that fixes it.

**Comment by lionhylra** [comment]
Please see my code below:
```objective-c
@interface LoginViewController()
@property (nonatomic, weak) IBOutlet FBShimmeringView * shimmerView;
@property (nonatomic, weak) IBOutlet UITextField * emailTextField;
@property (nonatomic, weak) IBOutlet UITextField * passwordTextField;
@property (nonatomic, weak) IBOutlet UIButton * loginButton;
@end
@implementation JLPLoginViewController
- (void)viewDidLoad {
    [super viewDidLoad];
    [self showLogo];
}
-(void)showLogo{
    UIImageView *imageView = [[UIImageView alloc] initWithFrame:self.shimmerView.bounds];
    imageView.image = [UIImage imageNamed:@"logo"];
    imageView.contentMode = UIViewContentModeScaleAspectFit;
    self.shimmerView.contentView = imageView;
    
    // Start shimmering.
    self.shimmerView.shimmering = YES;
}
@end
```
What I did is:
1. I instantiate the LoginViewController from storyboard in '- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions', and assign it to the rootViewController of main window
2. When the login button is tapped, I instantiate another view controller and assign to the rootViewController of main window. At this moment, the LoginViewController should have been deallocated.
3. When the logout button is tapped, instantiate a LoginViewController and assign it to the rootViewController of main window again. At this moment, the FBShimmeringLayer of previous LoginViewController is not deallocated and a new instance of FBShimmeringLayer is created for the new LoginViewController.

**Comment by lionhylra** [comment]
After trying the last commit, I find the issue is still there.  
![screenshot 2015-10-22 11 38 17](https://cloud.githubusercontent.com/assets/4083480/10654078/a795f052-78b1-11e5-9556-2eedbf8d7a70.png)
![screenshot 2015-10-22 11 38 36](https://cloud.githubusercontent.com/assets/4083480/10654080/af22a950-78b1-11e5-974c-51414ea06260.png)

**Comment by grp** [comment]
Unfortunately, you'll have to debug this yourself. It may be due to the specifics of how you're using `Shimmer`.
